baseURL = "https://factor10.github.com/intent"
languageCode = "en-us"
title = "Intent"
theme = "intent"

pygmentsuseclasses = false

[menu]

  [[menu.main]]
    identifier = "introduction"
    name = "Introduction"
    url = "/"
    weight = 100

  [[menu.main]]
    parent = "introduction"
    name = "Getting started"
    url = "#getting-started"
    weight = 100

  [[menu.main]]
    parent = "introduction"
    name = "Why a new framework"
    url = "#why-a-new-test-framework"
    weight = 110

  [[menu.main]]
    parent = "introduction"
    name = "Contributing"
    url = "#contributing-to-intent"
    weight = 120

  [[menu.main]]
    parent = "introduction"
    name = "Find us at GitHub"
    url = "https://github.com/factor10/intent"
    weight = 120

  [[menu.main]]
    identifier = "types"
    name = "Types of tests"
    url = "/types-of-tests/stateless/"
    weight = 200

  [[menu.main]]
    parent = "types"
    name = "Stateless"
    url = "/types-of-tests/stateless/"
    weight = 100

  [[menu.main]]
    parent = "types"
    name = "Stateful"
    url = "/types-of-tests/stateful/"
    weight = 110

  [[menu.main]]
    parent = "types"
    name = "Asynchronous"
    url = "/types-of-tests/asynchronous/"
    weight = 120

  [[menu.main]]
    parent = "types"
    name = "Table-driven"
    url = "/types-of-tests/table-driven/"
    weight = 130

  [[menu.main]]
    identifier = "matchers"
    name = "Matchers"
    url = "/matchers/"
    weight = 300

  [[menu.main]]
    parent = "matchers"
    name = ".toEqual"
    url = "/matchers/#toequal"
    weight = 110

  [[menu.main]]
    parent = "matchers"
    name = ".toHaveLength"
    url = "/matchers/#tohavelength"
    weight = 120

  [[menu.main]]
    parent = "matchers"
    name = ".toContain"
    url = "/matchers/#tocontain"
    weight = 130

  [[menu.main]]
    parent = "matchers"
    name = ".toContainAllOf"
    url = "/matchers/#tocontainallof"
    weight = 140

  [[menu.main]]
    parent = "matchers"
    name = ".toCompleteWith"
    url = "/matchers/#tocompletewith"
    weight = 150

  [[menu.main]]
    parent = "matchers"
    name = ".toMatch"
    url = "/matchers/#tomatch"
    weight = 160

  [[menu.main]]
    parent = "matchers"
    name = ".toThrow"
    url = "/matchers/#tothrow"
    weight = 170

  [[menu.main]]
    identifier = "customization"
    name = "Customization"
    url = "/customization/"
    weight = 400

  [[menu.main]]
    parent = "customization"
    name = "Manually fail or succeed"
    url = "/customization/#manually-fail-or-succeed"
    weight = 100

  [[menu.main]]
    parent = "customization"
    name = "Asyncness"
    url = "/customization/#asyncness"
    weight = 110

  [[menu.main]]
    parent = "customization"
    name = "Equality"
    url = "/customization/#equality"
    weight = 120

  [[menu.main]]
    parent = "customization"
    name = "Floating-point precision"
    url = "/customization/#floating-point-precision"
    weight = 130

  [[menu.main]]
    parent = "customization"
    name = "Formatting"
    url = "/customization/#formatting"
    weight = 140

  [[menu.main]]
    parent = "customization"
    name = "Timeout"
    url = "/customization/#timeout"
    weight = 150
